#!/usr/bin/env python3
import requests
from bs4 import BeautifulSoup

url = 'https://simple.wikipedia.org/wiki/Wikipedia:List_of_1000_basic_words'

r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
text = ' '.join(a.text for dl in soup.select('dl') for a in dl.select('a'))
print(text)
