name:  "Format code with python black"
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black . --check
      - name: Print diff
        if: failure()
        run: poetry run black . --diff
